name: Bandit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install bandit
      - name: Run bandit
        run: |
          bandit *.py
